services:
  - type: web
    name: kasip-agent
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python kasip_agent.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
